import "./globals.css";
import {Anton} from 'next/font/google'

const anton_init = Anton({subsets:['latin'],weight:['400'],variable:'--font-anton'})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[rgb(17,18,20)] ${anton_init.variable}`}>
        {children}
      </body>
    </html>
  );
}
